### ISSUE TITLE
Docker OCI runtime issue

### ISSUE THREAD

**Issue by privatesam** [JNoDuq/videobench#23]
Everything compiled and installed ok.  Now getting the following issue:

```* Analyzing Reference File...

docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"ffprobe\": executable file not found in $PATH": unknown.

time="2020-09-08T11:09:15+01:00" level=error msg="error waiting for container: context canceled"

Traceback (most recent call last):
  File "/home/sam/videobench/videobench.py", line 171, in <module>
    ref_obj = manage_ref_file(ref_file, loglevel)
  File "/home/sam/videobench/videobench.py", line 20, in manage_ref_file
    ffprobe_json = get_video_streams_info(filename, loglevel) ############ get video file info 
  File "/home/sam/videobench/videobench_functions.py", line 270, in get_video_streams_info
    result = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'docker container run --rm  -v /tmp/videobench/:/home/shared-vmaf/ docker-videobench ffprobe -loglevel quiet -print_format json -show_streams -select_streams v -i /home/shared-vmaf/Aiza.wmv.mp4' returned non-zero exit status 127.```

**Comment by JNoDuq** [comment]
Hello, I have updated the docker file. Can you try again? Thank you
