### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by Anas92230** [JNoDuq/videobench#4]
great job :-)
i have an error when I launch your script : 
* Analyzing Reference File...
Traceback (most recent call last):
  File "/u0/videoBench/videobenchMaster/videobench.py", line 169, in <module>
    ref_obj = manage_ref_file(ref_file)
  File "/u0/videoBench/videobenchMaster/videobench.py", line 20, in manage_ref_file
    ffprobe_json = get_video_streams_info(filename) ############ get video file info 
  File "/u0/videoBench/videobenchMaster/videobench_functions.py", line 267, in get_video_streams_info
    return json.loads(result)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Can you help me to resolve it?
Thank you

**Comment by JNoDuq** [comment]
Hi,

Can you tell me more about what you try to do ? Can you send me sample files ?

**Comment by JNoDuq** [comment]
I have add a log level option for try to understand when a video file does not go through the process

**Comment by Anas92230** [comment]
I'm going to try it now

**Comment by Anas92230** [comment]
*****************************
STARTING VIDEO BENCH
python3 /u0/videoBench/videobenchMaster/videobench.py -ref /home/ingetv/video_src/TEST_HD_35_Mb.ts -i /home/ingetv/video_src/TEST_HD_35_Mb.ts -sync 0 -sw 0.0 -deint auto -subsampling auto -scale neighbor -vmaf_model auto -loglevel info
*****************************
* Analyzing Reference File...

docker container run --rm  -v /tmp/videobench/:/home/shared-vmaf/ docker-videobench ffprobe -loglevel info -print_format json -show_streams -select_streams v -i /home/shared-vmaf/TEST_HD_35_Mb.ts

ffprobe version N-94060-g2fdbeb0b8c Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --enable-libvmaf --enable-version3
  libavutil      56. 29.100 / 56. 29.100
  libavcodec     58. 53.100 / 58. 53.100
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 55.100 /  7. 55.100
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100

[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced

[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced

[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] SPS unavailable in decode_picture_timing
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] non-existing PPS 0 referenced
[h264 @ 0x55a81ae63b00] decode_slice_header error
[h264 @ 0x55a81ae63b00] no frame!

[mpegts @ 0x55a81ae5e9c0] PES packet size mismatch

Input #0, mpegts, from '/home/shared-vmaf/TEST_HD_35_Mb.ts':
  Duration: 00:01:50.38, start: 24232.040133, bitrate: 34828 kb/s
  Program 410 
    Metadata:
      service_name    : Test HD
      service_provider: Television
    Stream #0:0[0x140]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x14a](fre): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 320 kb/s
    Stream #0:2[0x14b](qad): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 320 kb/s
    Stream #0:3[0x14c](qaa): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 320 kb/s
    Stream #0:4[0x155](fre,fre,fre): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)
Unsupported codec with id 94215 for input stream 4

**Comment by JNoDuq** [comment]
Can you send to me a sample file ?
