### ISSUE TITLE
Issue with JPG2000 files

### ISSUE THREAD

**Issue by wabiloo** [JNoDuq/videobench#5]
Hi,

When trying to work with a JPEG2000 bitstream (in my case, wrapped in an MXF container), I get the following error:

```* Analyzing Reference File...

Traceback (most recent call last):
  File "/Users/fabre.lambeau/Bitmovin/Tools/videobench/videobench.py", line 169, in <module>
    ref_obj = manage_ref_file(ref_file)
  File "/Users/fabre.lambeau/Bitmovin/Tools/videobench/videobench.py", line 32, in manage_ref_file
    ref_obj.avg_frame_rate = round((float(num)/float(den)),0)
ZeroDivisionError: float division by zero```

I can provide you with such a file if you don't have one

**Comment by JNoDuq** [comment]
Hi, send me a sample file, please.

**Comment by JNoDuq** [comment]
I have add a log level option for try to understand when a video file does not go through the process
