### ISSUE TITLE
No graphs showing + AV1 Support + Windows Support

### ISSUE THREAD

**Issue by aymacarena** [JNoDuq/videobench#6]
Hi,

got the software running today on the newest Ubuntu Live CD

Looks promising!

I tried analysing a few H.264 and VP9 files, I also get the results in the Command Line, but the Results screen freezes, no graphs are showing and output is:

```
ubuntu@ubuntu:~/Downloads/videobench-master$ sudo python3 videobench_ui.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Screen Size: 1680 x 1050
Traceback (most recent call last):
  File "videobench_ui.py", line 735, in update_ui
    self.check_init()
  File "videobench_ui.py", line 749, in check_init
    self.add_lineSeries(self.inputs_checkbox_vlayout.itemAt(i).widget())
  File "videobench_ui.py", line 241, in add_lineSeries
    self.add_lineSeries_seconds(input_widget)
  File "videobench_ui.py", line 259, in add_lineSeries_seconds
    name, ext = input_widget.objectName().split('.')
ValueError: too many values to unpack (expected 2)

```
Also when trying AV1 a error pops up:

```
* Analyzing Reference File...

Traceback (most recent call last):
  File "/home/ubuntu/Downloads/videobench-master/videobench.py", line 171, in <module>
    ref_obj = manage_ref_file(ref_file, loglevel)
  File "/home/ubuntu/Downloads/videobench-master/videobench.py", line 58, in manage_ref_file
    ref_obj.interlaced = round(sum(interlaced_frame_list)/len(interlaced_frame_list))
ZeroDivisionError: division by zero
```
Running it on Windows is a pain sadly, as all the paths in the *.py files are not Windows compatible, and the python3 (...) command inside videobench.py is not recognized. Even then, a lot of multithreading errors popup and the error above occur.

Hope this helps! Would love to use this script!

**Comment by JNoDuq** [comment]
Sorry for my very late answer... Can you tell me what is the name of your tests files ?
